import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { storyblokInit, apiPlugin } from "@storyblok/react/rsc";
import { StoryblokProvider } from "@/components/StoryblokProvider";
import Link from "next/link";
import { draftMode } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

let enableCaching: boolean = true;

export const disableCaching = (): void => {
  enableCaching = false;
};

const cachedFetch = (input: any, init?: any): Promise<Response> => {
  if (enableCaching) {
    const { isEnabled } = draftMode();
    return fetch(input, {
      ...init,
      cache:
        process.env.NODE_ENV === "development" || isEnabled
          ? "no-store"
          : "force-cache",
    });
  } else {
    enableCaching = true;
    return fetch(input, {
      ...init,
      cache:
        process.env.NODE_ENV === "development" ? "no-store" : "force-cache",
    });
  }
};

storyblokInit({
  accessToken: process.env.STORYBLOK_TOKEN,
  use: [apiPlugin],
  apiOptions: {
    fetch: cachedFetch,
  },
});

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <StoryblokProvider>
      <html lang="en">
        <body className={`${inter.className} bg-blue-50`}>
          <header>
            <nav className="component py-8 flex justify-between">
              <Link href={"/"}>Home</Link>
              <Link href={"/tours"}>Tours</Link>
            </nav>
          </header>
          {children}
        </body>
      </html>
    </StoryblokProvider>
  );
};

export default RootLayout;
